08 lection6 postcss
js-tasks-ru/htmlcss-20210916_viktor-minor pull request #21
Opened 2021-10-13 21:52 UTC by ma4ete44

2021-10-13 21:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-14 16:56 UTC, GSemikozov requested changes

2021-10-14 16:56 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +  <link rel='stylesheet' href="../../assets/css/main.scss">
ошибочка, подключать должны css

2021-10-14 16:56 UTC, GSemikozov commented on components/toggler/toggler.scss
> +.toggler {
в целом по ПР-у - нигде не вижу одной из основных фишек препроцессора - вложенности селекторов)) ну и миксинов, переменных.

2021-10-15 11:47 UTC, merged