add themed buttons
js-tasks-ru/htmlcss-20210916_viktor-minor pull request #3
Opened 2021-09-22 21:53 UTC by ma4ete44

2021-09-22 21:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-23 16:16 UTC, GSemikozov requested changes

2021-09-23 16:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: white;
цвет важно забрать из переменных

2021-09-23 16:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button:disabled {
button -> .button

2021-09-23 17:24 UTC, ma4ete44 commented on 03-lection1/01-button/button.css
> +    color: white;
fix

2021-09-23 17:24 UTC, ma4ete44 commented on 03-lection1/01-button/button.css
> +button:disabled {
fix

2021-09-24 12:58 UTC, GSemikozov approved these changes

2021-09-24 12:58 UTC, merged