add histogram
js-tasks-ru/htmlcss-20210916_viktor-minor pull request #6
Opened 2021-09-27 06:38 UTC by ma4ete44

2021-09-27 06:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-27 15:06 UTC, GSemikozov requested changes

2021-09-27 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__left-part__title {
в БЭМ избегаем использование элементов элементов - это будет ошибкой. Гораздо правильнее - максимально плоская структура. Поэтому нужно и сами классы переписать и продумать, например - .histogram__title, .histogram__count, .histogram__link

2021-09-27 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__left-part__total-score {
тут то же самое

2021-09-27 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__button {
и тут (это на самом деле .histogram__link)

2021-09-27 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
такой вариант выравнивания столбцов не подойдет (проверить нужно так: оставить 1-2 колонки)

2021-09-27 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__content > .histogram__content__item:not(:last-child) {
вложенные селекторы тоже не стоит использовать (можно просто .histogram__content-item:last-child)

2021-09-27 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__content__item {
.histogram__content-item

2021-09-27 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
высота уже задается инлайном

2021-09-27 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
вместо такого варианта правильнее. комбинация из flex:basis: 9px + flex-grow: 1 (совету проверить на том же кейсе, когда у нас в чарте всего 1 или 2 колонки)

2021-09-28 10:00 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
fixed

2021-09-28 10:00 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
fixed

2021-09-28 10:00 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__content__item {
fixed

2021-09-28 10:00 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__content > .histogram__content__item:not(:last-child) {
fixed

2021-09-28 10:01 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
fixed

2021-09-28 10:01 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__button {
fixed

2021-09-28 10:01 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__left-part__total-score {
fixed

2021-09-28 10:01 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__left-part__title {
fixed

2021-09-28 18:04 UTC, GSemikozov requested changes

2021-09-28 18:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 4px;
1px  ?)

2021-09-28 21:09 UTC, ma4ete44 commented on 04-lection2/01-histogram/histogram.css
> +    gap: 4px;
fixed

2021-09-29 17:23 UTC, GSemikozov approved these changes

2021-09-29 17:23 UTC, merged